# Generated by Django 5.0.6 on 2024-08-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='carty',
        ),
    ]
