# Generated by Django 5.0.6 on 2024-08-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carty',
            name='price',
            field=models.IntegerField(),
        ),
    ]
