# Generated by Django 5.0.6 on 2024-08-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_carty_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carty',
            name='price',
            field=models.FloatField(),
        ),
    ]
