# Generated by Django 5.0.6 on 2024-08-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_carty_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carty',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
